### ISSUE TITLE
" warning: unused variable 'size' " In Arduino ide 2

### ISSUE THREAD

**Issue by WRoss7** [xreef/EByte_LoRa_E220_Series_Library#10]
c:\< PATH >\LoRa_E220.cpp: In member function 'void LoRa_E220::writeProgramCommand(PROGRAM_COMMAND, REGISTER_ADDRESS, PACKET_LENGHT)':
c:\< PATH >\LoRa_E220.cpp:552:12: warning: unused variable 'size' [-Wunused-variable]
    uint8_t size = this->serialDef.stream->write(CMD, 3);
            ^

However, everything works great

**Comment by xreef** [comment]
Thanks WRoss7,
I'm going to fix.
Bye Renzo
