### ISSUE TITLE
how to set the module to deep sleep

### ISSUE THREAD

**Issue by homonto** [xreef/EByte_LoRa_E220_Series_Library#15]
First I would like to say thank you for your great job.
Second: E220 module is capable of going to deep sleep.
But I am missing such method in your library.
Could you please advise how to send E220 to deep sleep and wake it then later?
I would assume by providing HIGH/LOW to M0 and M1 right, but do I need to do it on my own (digitalWrite(M0, HIGH/LOW) or it is there already?

thank you

**Comment by homonto** [comment]
so I added to my code:

```
#define AUX   18
#define M0    19
#define M1    21

LoRa_E220 e220ttl(&Serial2, AUX, M0, M1);

pinMode(AUX, INPUT);
pinMode(M0, OUTPUT);
pinMode(M1, OUTPUT);
```

and then:
```
void sleep()
{
  digitalWrite(M0, 1);
  digitalWrite(M1, 1);
}

void wakeup()
{
    digitalWrite(M0, 0);
    digitalWrite(M1, 0);
}
```

I think that does the job - at least I can see it does ;-)

**Comment by xreef** [comment]
Hi homonto,
for example It's important that you specify the microcontroller; I write some articles about sleep and WOR.

For E220.
[Here ](https://mischianti.org/2022/05/06/ebyte-lora-e220-device-for-arduino-esp32-or-esp8266-manage-wake-on-radio-and-sends-structured-data-5/)you can check the management of sleep of the LoRa module, but without the control of microcontroller.

For the E32 that uses the equivalent library, I developed (something changed but not the management of the microcontroller).
[Here ](https://mischianti.org/2021/04/14/ebyte-lora-e32-device-for-arduino-esp32-or-esp8266-wor-wake-on-radio-and-new-esp32-shield-8/)you can check how to manage and persist the pin values of M0 and M1 with an esp32, [here ](https://mischianti.org/2020/01/17/lora-e32-device-for-arduino-esp32-or-esp8266-wor-wake-on-radio-microcontroller-and-new-wemos-d1-mini-shield-part-7/)with an esp8266 and [here ](https://mischianti.org/2019/12/28/lora-e32-device-for-arduino-esp32-or-esp8266-wor-wake-on-radio-the-microcontroller-also-and-new-arduino-shield-part-6/)with Arduino UNO

Tell me if you can find your needs. 

And if you write to the support forum, I think you can find more help.

Bye Renzo

**Comment by homonto** [comment]
thank you
Since I will use LoRa for my remote sensors, I actually don't need WOR - I just want to:
1- wake up ESP32 from deep sleep
2- provide M0 and M1 LOW to wake E220 completely
3- check sensors
4- send data over LoRa
5- provide M0 and M1 HIGH to put to sleep E220 completely
6- deep sleep for ESP32 until next cycle

this way I would save a lot of power - E220 power consumption I just measured:
TX mode:
<img width="1628" alt="0-tx" src="https://github.com/xreef/EByte_LoRa_E220_Series_Library/assets/46562447/b60f11a4-c007-4c79-afa6-eed54f92747a">

RX mode:
<img width="1630" alt="0-rx" src="https://github.com/xreef/EByte_LoRa_E220_Series_Library/assets/46562447/9d540970-f5a5-4ece-bab8-24523d15f588">

Sleep mode:
<img width="1624" alt="0-sleep" src="https://github.com/xreef/EByte_LoRa_E220_Series_Library/assets/46562447/107750ce-f332-4da8-ac00-694253905fc7">


One thing I am surprised is the time it takes to send the message: from the graph we can see around 340ms while millis() show ... 20ms - I am not sure where the catch is - it is kind of 17 times more ;-)

**Comment by homonto** [comment]
OK, I found out the difference between 20ms and 340ms
So these lines take 20ms:
```
  ResponseStatus rs = e220ttl.sendMessage(&struct1, sizeof(struct1));
  Serial.print(rs.getResponseDescription()); 
```
but even if we see "Success" it does NOT mean the data was sent.
Only adding this line:
```
while (digitalRead(AUX) == 0) {}
```
makes sure it was really sent.
And waiting for AUX to become LOW takes around 340ms, during which the message is really sent:

```
  Serial.print("Checking AUX status...");
  long start = millis();
  while (digitalRead(AUX) == 0) {}
  Serial.println("HIGH, it took " + String(millis()-start)+"ms");
```

and it outputs:
```
Checking AUX status...HIGH, it took 360ms
```

So I am not sure if I am not using your library properly, or really sendMessage(...) method does not wait for the message to be sent.

Of course few milliseconds are lost during the debugging (Serial.print etc.) but the idea was: what make the difference between 20ms vs 360ms shown by measuring power

**Comment by homonto** [comment]
what I am trying to say is: if you want to go to sleep (E220) without checking AUX, you might end up thinking message was sent, while in fact it was not sent and "ResponseStatus rs" does NOT help with that at all.
That is my finding

**Comment by xreef** [comment]
Hi,
Yes it's true, if you don't set Aux, I use an estimated time that cover all case (I try to use less time but I discover a lot of issue), and it's surely not so efficient, to get better efficiency you must connect AUX.
Bye Renzo
