### ISSUE TITLE
is AUX necessary?

### ISSUE THREAD

**Issue by garudaonekh** [xreef/EByte_LoRa_E220_Series_Library#16]
HI,
As per your description, AUX is not required.
But without AUX, available() function return 0. availabe() is fine when I use AUX pin

I use ESP32 custom PINs.

**Comment by xreef** [comment]
Hi,
AUX isn't necessary, but isn't efficient because AUX advise that the operation is successful executed if isn't connected I wait a long time that cover all possible operations, so It waste a lot of time.
Bye Renzo

**Comment by garudaonekh** [comment]
Ok, I set 1 second timeout to wait for reply.  My receiver immediately response back. Can we adjust your wait time? I do not have any pin left for AUX

**Comment by xreef** [comment]
Hi,
the library already have inside a tested wait that cover all situation.
You don't add any other wait.
Bye Renzo
