### ISSUE TITLE
Switching to 868MHz does not work

### ISSUE THREAD

**Issue by WotoAOT** [xreef/EByte_LoRa_E220_Series_Library#20]
Hello,
I have the E220-900T22D module and when I query the transmission frequency via getChannelDescription(), I get 433Mhz.
Via #define FREQUENCY_868 I want to set the transmission frequency to 868MHz. But this does not work. What could be the reason for this?

Best regards
Woto

**Comment by xreef** [comment]
You can find some informations here.
https://mischianti.org/forums/topic/esp8266-wemos-d1-mini-and-e220-900t30d-frequencies-problem-and-info/
Bye Renzo

**Comment by WotoAOT** [comment]
Hello Renzo,
Thank you very much. It works now. 
Best regards,
Woto
